title: Choi Hannah Okkoung
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://hannah30.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: https://github.com/hannah30
   instagram: https://www.instagram.com/hannah29/
   facebook: https://www.facebook.com/okkoung.choi
   email: watasikei@gmail.com

google_analytics: "UA-58263416-1"
